### ISSUE TITLE
Voice channel leave behaviour

### ISSUE THREAD

**Issue by lus** [DRSchlaubi/mikmusic#28]
Currently the bot leaves immediately if there is no song remaining in the queue. In my opinion it would be nice if one could configure a timeout which has to exceed before he does so.

He also does not stop playing music if no user is left in the voice channel which wastes some server resources. This would also be a nice thing to implement.

**Comment by DRSchlaubi** [comment]
Should this be a global or a server setting

**Comment by lus** [comment]
I think a server setting would be nice

**Comment by DRSchlaubi** [comment]
Fixed in 28695b5
